# Generated by the Update formula workflow. Do not edit by hand.
class SoulseekRs < Formula
  desc "Soulseek client in Rust"
  homepage "https://re-invention.nl/soulseek-rs/"
  version "9.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/michel/soulseek-rs/releases/download/v9.0.0/soulseek-rs-v9.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "bff385a58f17c5eaf70f1c08d11fa55a68c2f6e352d697054268948b55ab921d"
    end
    on_intel do
      url "https://github.com/michel/soulseek-rs/releases/download/v9.0.0/soulseek-rs-v9.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "884fdaba5cf7be308bffe0ce58edbde685606472f6e1a6805583124175465b6d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/michel/soulseek-rs/releases/download/v9.0.0/soulseek-rs-v9.0.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "8152d649ab8a99c63e37b6b63f6db9be1ac40a2c1110e3bb67fc8eae4173352b"
    end
    on_intel do
      url "https://github.com/michel/soulseek-rs/releases/download/v9.0.0/soulseek-rs-v9.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "99e33f8ff568be583c1f4c462bf841d37eb014f12f80d3249df7843c2c4a4ee7"
    end
  end

  def install
    bin.install "soulseek-rs"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/soulseek-rs --version")
  end
end
