# Generated by the Update formula workflow. Do not edit by hand.
class SoulseekRs < Formula
  desc "Soulseek client in Rust"
  homepage "https://re-invention.nl/soulseek-rs/"
  version "13.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/michel/soulseek-rs/releases/download/v13.0.0/soulseek-rs-v13.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "b6e0dbd8db44681fbada8c464a6c4a7c0f4dfbd7e272c05b72a45772dcc21cf3"
    end
    on_intel do
      url "https://github.com/michel/soulseek-rs/releases/download/v13.0.0/soulseek-rs-v13.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "91f5c7596a0a10a7029d4f97460a493c5f7f4e84a1079a4b07379bd193c4f9ec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/michel/soulseek-rs/releases/download/v13.0.0/soulseek-rs-v13.0.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "081102c9f3557d48f43a374722428a1bd13a8a18505e8f642a0da967fece69bf"
    end
    on_intel do
      url "https://github.com/michel/soulseek-rs/releases/download/v13.0.0/soulseek-rs-v13.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "fd4d323f03391ee7d92bed221a0f4d41c42c797d8f12d9d93025cf2bb3d89e67"
    end
  end

  def install
    bin.install "soulseek-rs"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/soulseek-rs --version")
  end
end
